name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute tests with coverage
        run: ./gradlew runOnGitHub

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: List files
        run: |
          ls -la .github

      - name: Commit and push the badge (if it changed)
          uses: EndBug/add-and-commit@v9
          with:
            author_name: "github-actions[bot]"
            author_email: "github-actions[bot]@users.noreply.github.com"
            message: 'commit badge'
            add: '*.svg'
            push: true
            token: ${{ secrets.ACTIONS_PAT }}

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/
